# Generated by Django 5.0.7 on 2024-07-17 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_dataset_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='folder_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
